# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options

language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.2.7
  - DJANGO=1.3.7
  - DJANGO=1.4.5

install:
  - sudo pip install -q Django==$DJANGO --use-mirrors
  - sudo pip install -r test/example_thirdparty/requirements.txt -r test/example_thirdparty/requirements_test.txt

script:
  - python test/example_thirdparty/manage.py test pybb

