# https://github.com/travis-ci/travis-ci/wiki/.travis.yml-options

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install Pillow -U
  - pip install -r test/test_project/requirements_test.txt
script:
  - python setup.py test

